import React from 'react'

export const s = {
  container: { padding: '20px 24px', fontFamily: 'inherit' } as React.CSSProperties,
  sectionBlock: { marginBottom: 28 } as React.CSSProperties,
  sectionHeader: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    color: '#6E52EB',
    marginBottom: 10,
    paddingBottom: 6,
    borderBottom: '1px solid #2E3138',
  },
  groupCard: {
    background: '#1A1C23',
    border: '1px solid #2E3138',
    borderRadius: 8,
    marginBottom: 10,
    overflow: 'hidden',
  } as React.CSSProperties,
  groupHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    background: '#1E2028',
    borderBottom: '1px solid #2E3138',
  } as React.CSSProperties,
  groupTitle: { fontSize: 12, fontWeight: 600, color: '#E8E8E8' } as React.CSSProperties,
  groupMeta: { fontSize: 11, color: '#9A9FA8', marginLeft: 8 } as React.CSSProperties,
  exerciseRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '7px 12px',
    borderBottom: '1px solid #23252D',
    gap: 8,
  } as React.CSSProperties,
  exerciseNumer: { fontSize: 11, fontWeight: 700, color: '#6E52EB', minWidth: 28 } as React.CSSProperties,
  exerciseName: { fontSize: 13, color: '#E8E8E8', flex: 1 } as React.CSSProperties,
  exerciseMeta: { fontSize: 11, color: '#9A9FA8' } as React.CSSProperties,
  btnDanger: {
    background: 'transparent',
    border: 'none',
    color: '#EF4444',
    cursor: 'pointer',
    fontSize: 11,
    padding: '2px 6px',
    borderRadius: 4,
  } as React.CSSProperties,
  btnAdd: {
    background: 'transparent',
    border: '1px dashed #3E4149',
    color: '#9A9FA8',
    cursor: 'pointer',
    fontSize: 12,
    padding: '6px 12px',
    borderRadius: 6,
    width: '100%',
    textAlign: 'left' as const,
    marginTop: 4,
  },
  btnPrimary: {
    background: '#6E52EB',
    border: 'none',
    color: '#fff',
    cursor: 'pointer',
    fontSize: 12,
    padding: '6px 14px',
    borderRadius: 6,
    fontWeight: 600,
  } as React.CSSProperties,
  btnSecondary: {
    background: 'transparent',
    border: '1px solid #3E4149',
    color: '#9A9FA8',
    cursor: 'pointer',
    fontSize: 12,
    padding: '6px 14px',
    borderRadius: 6,
  } as React.CSSProperties,
  formBox: {
    background: '#13141A',
    border: '1px solid #2E3138',
    borderRadius: 8,
    padding: '12px 14px',
    marginTop: 8,
  } as React.CSSProperties,
  formRow: { display: 'flex', gap: 8, flexWrap: 'wrap' as const, marginBottom: 8 } as React.CSSProperties,
  label: { fontSize: 11, color: '#9A9FA8', display: 'block', marginBottom: 3 } as React.CSSProperties,
  input: {
    background: '#1A1C23',
    border: '1px solid #2E3138',
    borderRadius: 5,
    color: '#E8E8E8',
    fontSize: 13,
    padding: '5px 8px',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  select: {
    background: '#1A1C23',
    border: '1px solid #2E3138',
    borderRadius: 5,
    color: '#E8E8E8',
    fontSize: 13,
    padding: '5px 8px',
    width: '100%',
  },
  formActions: { display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 10 } as React.CSSProperties,
  empty: { fontSize: 12, color: '#9A9FA8', padding: '8px 12px', fontStyle: 'italic' as const },
  errorMsg: { fontSize: 12, color: '#EF4444', marginBottom: 8 },
}
